### ISSUE TITLE
Invite

### ISSUE THREAD

**Issue by Jollyfant** [EIDA/EIDA#1]
Hi Petrr, can you invite me to the organization? 

We would like to make this the main repository for officially publishing code within EIDA.

Maybe these guys too:
@javiquinte @andres-h @ltrani

**Comment by petrrr** [comment]
@Jollyfant apologies for the delay, I have given less attention to my GitHub notifications lately. (I was out of office for some time and suffered from a burst of work load afterwards).

You should have received a notification. If you need a different role just recontact me o @ltrani.

**Comment by andres-h** [comment]
I used to push to EIDA/seiscomp3 few months ago, but I don't have the permission anymore :(

**Comment by andres-h** [comment]
@petrrr @ltrani Can you please give me write access or should I use another repository?

**Comment by Jollyfant** [comment]
> @petrrr @ltrani Can you please give me write access or should I use another repository?

Me too `remote: Permission to EIDA/EIDA.git denied to Jollyfant.`

**Comment by petrrr** [comment]
@andres-h @Jollyfant: The role and rights system seems to have changed.  Does it work now? You should be able to write to all repos and to create new ones.

**Comment by petrrr** [comment]
@andres-h BTW, are you aware of the fact that EIDA/seiscomp3 is only the fork of SeisComP3/seiscomp3?

**Comment by andres-h** [comment]
On 10/13/2016 06:52 PM, petrrr wrote:
> @andres-h @Jollyfant: The role and rights system seems to have
> changed. Does it work now? You should be able to write to all repos and
> to create new ones.

Yes, seems to work now.

**Comment by andres-h** [comment]
On 10/13/2016 06:54 PM, petrrr wrote:
> @andres-h BTW, are you aware of the fact that EIDA/seiscomp3 is only the fork of SeisComP3/seiscomp3?

EIDA developments were merged into SC3 master today, so both branches 
are in fact identical now.

I had to do a rebase (requested by SC3 devs to clean up the pull 
request), so sorry if someone had cloned EIDA/seiscomp3 previously.

**Comment by Jollyfant** [comment]
Writing is OK for me too. I'm pushing WFCatalog source to this repository, and maybe we can include the routing source code as well so we have everything in one repo instead of making separate ones for each service. @javiquinte

**Comment by andres-h** [comment]
On 10/14/2016 09:37 AM, Jollyfant wrote:
> Writing is OK for me too. I'm pushing WFCatalog source to this
> repository, and maybe we can include the routing source code as well so
> we have everything in one repo instead of making separate ones for each
> service. @javiquinte

IMHO, this is not a good idea at all. There are several several forks of 
individual projects, eg.:

https://github.com/EIDA/webdc3 vs. https://github.com/andres-h/webdc3
https://github.com/EIDA/routing vs. https://github.com/GEOFON/routing
etc.

What's wrong with having individual repositories under EIDA account? I'd 
also prefer EIDA/wfcatalog instead of EIDA/EIDA/wfcatalog.

I want to fork only the projects I'm working on, not all EIDA software. 
Moreover, if rebase is needed, it would only affect a single repository.

Regards,
Andres.

**Comment by Jollyfant** [comment]
On the other hand, if you do have a copy of all the EIDA software (so not Seiscomp) under one repo it becomes easier to contribute and keep an eye on the development of the other projects. I have no problem making them individuals repos.

**Comment by Jollyfant** [comment]
WFCatalog is now in its own repo under EIDA/wfcatalog and everyone should have rights to make repos.

Closing this issue.

**Comment by petrrr** [comment]
@andres-h @Jollyfant 
Just to conclude the discussion here. My original idea was exactly what @andres-h was proposing, i.e. each product would have its own project/repo. The EIDA project was thought as a sort of landing page with a `README.md`, which would provide the pointer to the different projects

But of cause you are free to agree on any structure and adapt the organizations layout to the needs.
